### ISSUE TITLE
Reg Connector and Tasks Restart 

### ISSUE THREAD

**Issue by AishD3** [strimzi/proposals#109]
Hi , 

I am writing with respect to connector and tasks restarts . Would like to know , what would be the difference between Solution in 
https://strimzi.io/blog/2023/01/25/auto-restarting-connectors/ and Proposal document which is recently added here https://github.com/strimzi/proposals/blob/main/007-restarting-kafka-connect-connectors-and-tasks.md.

**Comment by scholzj** [comment]
This is not the right place to ask that. Please start a discussion: https://github.com/orgs/strimzi/discussions
